language: node
script:
  - npm install
  - npm run build-for-deploy
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  fqdn: www.ambulanceservice.com.sg
  local-dir: dist
  on:
    branch: nuxt
